apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pvc.fullname" . }}-secret
  labels:
    {{- include "pvc.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
{{- if .Values.secrets }}
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
