version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    groups:
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: 'zod'
        update-types: ['version-update:semver-major']
      - dependency-name: 'pino'
        update-types: ['version-update:semver-major']
      - dependency-name: 'pino-pretty'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vitest'
        update-types: ['version-update:semver-major']
      - dependency-name: 'prisma'
        update-types: ['version-update:semver-major']
      - dependency-name: '@prisma/client'
        update-types: ['version-update:semver-major']
      - dependency-name: 'lint-staged'
        update-types: ['version-update:semver-major']
