apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-server
  namespace: pvc
  labels:
    app.kubernetes.io/name: prompt-version-control
    app.kubernetes.io/component: server
automountServiceAccountToken: false
